apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport-service
  namespace: kafka
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: kafka
  selector:
    app: kafka
  sessionAffinity: None
  type: LoadBalancer